module.exports = [
  `**FREE`,
  ``,
  `Ctl-Opt DFTACTGRP(*NO);`,
  ``,
  `Dcl-Pi OPENMBR;`,
  `  pLib Char(10);`,
  `  pSPF Char(10);`,
  `  pMbr Char(10);`,
  `  pExt Char(10);`,
  `End-Pi;`,
  ``,
  `dcl-pr writeJobLog int(10) extproc('Qp0zLprintf');`,
  `  *n pointer value options(*string); // logMsg`,
  `  *n pointer value options(*string:*nopass);`,
  `end-pr;`,
  ``,
  `dcl-c joblogCRLF const(x'0d25');`,
  ``,
  `writeJobLog('C4I:open:'`,
  `          + %trim(pLib) + '/'`,
  `          + %trim(pSpf)`,
  `          + '/'`,
  `          + %trim(pMbr)`,
  `          + '.'`,
  `          + %trim(pExt)`,
  `          + '%s':joblogCRLF);`,
  ``,
  `Return;`,
];