on:
  pull_request:    
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  pull-request-build:
    uses: codefori/.github/.github/workflows/pr_build.yaml@main
    with:
       publish_types: true