on:
  release:
    types: [created]

permissions:
  id-token: write  # Required for OIDC
  contents: write
  
jobs:
  publish-release:
    uses: codefori/.github/.github/workflows/release.yaml@main
    with:
       publish_types: true
    secrets: inherit
